### ISSUE TITLE
Speed Challenge: Recreate derringibbs.com

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-derrin-gibbs#1]
Go to derringibbs.com and recreate that site from scratch using Bootstrap. 

Everything has to look AND behave the same way.

Be sure to create a gh-pages branch as well. 

due:
11-26-15   9p

updated due:
11-29-15   8p

**Comment by rampage1213** [comment]
Done!

**Comment by rampage1213** [comment]
This is all done but do I need to FTP this?

**Comment by rodneystrong** [comment]
Good job! No need to FTP.

**Comment by rodneystrong** [comment]
First off, no need to take care of this right now. Apologies for you getting notified the day after Thanksgiving but I had a free moment and I wanted to do this before I forgot about it. 

Here's some video feedback I have about your site that I'd like you to watch and take action on. If possible, please finish by Nov 29 8p. Feel free to push back the deadline if you need to; I also disclose this at the end of the video. 

http://somup.com/coXunsrco


due:
11-29-15    8p

**Comment by rampage1213** [comment]
Sorry about the late replay. Im getting started on this right now will be done tonight

**Comment by rampage1213** [comment]
All Done!

**Comment by rodneystrong** [comment]
Unfortunately there are still issues. Please talk to me for more details.

**Comment by rodneystrong** [comment]
Remember, Bootstrap has powerful class names built into its framework, but you have to fully understand how to use them before you use them all over your code. This might be an extreme example, but it's similar to not fully understand how your car works before driving it everywhere; there will be features that could save you time and headache that you're not taking advantage of.

**Comment by rampage1213** [comment]
All Done!

**Comment by rodneystrong** [comment]
Quintin, please make an effort to notate what problems you ran into and what you did to correct them. I know it's been a few days since you looked at this, but try to remember what happened; you can also look at your commit history to jog your memory in addition to my previous comments on this issue. 
It's important to solve the issue, but equally if not MORE important to understand how it happened and articulate how you resolved it.

due: 12-12-15    3p

**Comment by rampage1213** [comment]
When creating this static site I came across some styling issues. One of which was not using bootstraps preset containers for responsiveness, instead of doing that I was adding unnecessary media queries. I also forgot bootstraps viewport for mobile view 
~~~
<meta name="viewport" content="width=device-width, initial-scale=1">
~~~
In the long run, I was adding unnecessary margins instead of letting bootstrap do the work for me

**Comment by rodneystrong** [comment]
good work. over time your explanations will become more familiar and permanent in your memory.
