### ISSUE TITLE
Add clickable triangle to buttons

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-derrin-gibbs#2]
Go to derringibbs.com and look at the blue buttons titled "Facilities Maintenance", "Manufacturing", and Commercial/Industrial Construction". 

While they look like buttons, it's still a little unclear if visitors should click on them. 

Meg, I want you to implement the same code you wrote for the "law template" you made here: http://editllc.github.io/law-template/

Specifically the code that puts a triangle in the button that tells the user he/she can click on that button to see more info. 

In this instance, don't just use a black triangle though, find or create a triangle that follows the theme of the derringibbs.com site; maybe a white triangle with a white circle around it. I leave it up to your judgement. 

Remember, we want to give the user an undeniable impression that he/she can *and should* click on those blue buttons to see more info.

I also want you to explain your code to @jperez4509 and @rampage1213 . Schedule a teaching session with them. 

due:
12-17-15  5p

**Comment by rodneystrong** [comment]
I forgot to mention, you'll need to FTP these changes as well. 

Unfortunately @jarantfos is out of town, but again, please have the session with @jperez4509 and @rampage1213 by today's due date.

**Comment by rodneystrong** [comment]
Following up on this. Please respond by 12-19-15 3p with an updated due date you can reach.

**Comment by vanderbeam** [comment]
I've made progress as far as getting everything implemented except for the flip of the arrow. It should be done soon though. I'm sure it's just a minor detail I'm missing.

**Comment by vanderbeam** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12962001/11916127/13621c3a-a67e-11e5-8014-612d7c45dd69.png)

FINALLY.... there was a couple classes off but I got the arrows working now!
For some reason my Git Bash is giving me issues again so I can upload it to github so you can see it live but is the screen shot what you have in mind for the dropdown arrows? I kinda liked them better when they were just white arrows pointing up or down though but you mentioned wanting a background.

**Comment by rodneystrong** [comment]
Hmm.. This isn't good. We need to solve the issue behind your command line not allowing you to upload. 

Let's do a remote desktop session tomorrow at 3pm to settle this. 

Please take a screenshot of the errors your having and upload them here before our meeting tomorrow.

**Comment by rodneystrong** [comment]
Go to this link and download teamviewer full version: https://www.teamviewer.com/en/download/windows.aspx

**Comment by rodneystrong** [comment]
excellent work Megan. 

once you've done the session with @jperez4509 @rampage1213 and @jarantfos , please close this issue.

**Comment by rodneystrong** [comment]
Don't forget, I want you to school @jperez4509 and @rampage1213 on this. Sooner than later if possible.
