### ISSUE TITLE
Emailed changes from the client. 

### ISSUE THREAD

**Issue by rcsargent** [EditLLC/client-derrin-gibbs#4]
Richard, Please remove Thermal Energy Solutions and their contact information from my site. Thank you, your effort is appreciated. Derrin

**Comment by rodneystrong** [comment]
Assigning to you @rampage1213 . 

Remember to make sure to double-check if gh-pages looks the same as live, push the changes to gh-pages, then FTP to live

**Comment by rampage1213** [comment]
Done!
